// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CrudApi.DataModels
{
    [Index("IdUser", Name = "IX_Worker", IsUnique = true)]
    public partial class Worker
    {
        [Key]
        public int Id { get; set; }
        public int IdUser { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Salary { get; set; }
        public int YearsOfExperience { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LeavingDate { get; set; }

        [ForeignKey("IdUser")]
        [InverseProperty("Worker")]
        public virtual Users IdUserNavigation { get; set; }
    }
}